# Minimal GitHub Actions workflow to run Pester tests and linting on every push and pull request
name: Pester & Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pester
        shell: pwsh
        run: |
          Install-Module Pester -Force -Scope CurrentUser

      - name: Run Pester tests
        shell: pwsh
        run: |
          Invoke-Pester ./GetGovData.Tests.ps1

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Run PSScriptAnalyzer (lint all scripts)
        shell: pwsh
        run: |
          $results = Invoke-ScriptAnalyzer -Path . -Recurse -Severity Error
          if ($results) {
            $results | Format-Table | Out-String | Write-Host
            Write-Error "Linting errors found."
            exit 1
          } else {
            Write-Host "No linting errors found."
          }

# This workflow runs Pester unit tests and PSScriptAnalyzer linting on every push and pull request using PowerShell 7.x.
# The build will fail if any test or linting error is found, ensuring code quality and test coverage.
